services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: futebol_postgres
    environment:
      POSTGRES_DB: futebol_db
      POSTGRES_USER: futebol_user
      POSTGRES_PASSWORD: futebol_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - futebol_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U futebol_user -d futebol_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: futebol_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - futebol_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: futebol_redis
    command: redis-server --appendonly yes --requirepass ""
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - futebol_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Aplicação Java (WildFly 37 - compatível com Jakarta EE 10 e Java 21)
  wildfly:
    image: quay.io/wildfly/wildfly:latest
    container_name: futebol_wildfly
    environment:
      JAVA_OPTS: "-Xms512m -Xmx1024m -Djava.net.preferIPv4Stack=true -Duser.timezone=America/Sao_Paulo"
      JBOSS_MODULES_SYSTEM_PKGS: "org.jboss.logmanager"
      TZ: "America/Sao_Paulo"
    ports:
      - "8080:8080"   # HTTP
      - "9990:9990"   # Admin Console
    volumes:
      - ./target/gerenciador-jogos-1.0.0.war:/opt/jboss/wildfly/standalone/deployments/gerenciador-jogos.war
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - futebol_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/gerenciador-jogos/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local

networks:
  futebol_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Configurações adicionais
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
